apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: mlsdkqmskfsdfmlskf/demoapp:2.0.0
        ports:
        - containerPort: 8080

        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /actuator/health/readiness
            port: 8080

        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /actuator/health/liveness
            port: 8080

        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
